[package]
name = "jcode-operator-backend"
version = "0.1.0"
edition = "2024"
license = "MIT"
publish = false

[dependencies]
async-trait = "0.1"
automonique-platform-client = { git = "https://github.com/bext-stack/automonique.git", rev = "66e04e72741b5ffba0be8da6e757d67aae0232b1" }
automonique-protocol = { git = "https://github.com/bext-stack/automonique.git", rev = "66e04e72741b5ffba0be8da6e757d67aae0232b1" }
tokio = { version = "1", features = ["macros", "rt", "sync"] }

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
dbg_macro = "forbid"
todo = "forbid"
unimplemented = "forbid"
